---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.mydomain.com
  resources:
  - customsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.mydomain.com
  resources:
  - customsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - app.mydomain.com
  resources:
  - customsecrets/status
  verbs:
  - get
  - patch
  - update
